EVALUATE
CALCULATETABLE(
    FILTER(
        SUMMARIZECOLUMNS(
            DimDate[year],
            "Sales", [Total Sales]
        ),
        [Sales] > 0
    )
    /*__FILTERS__*/
)
ORDER BY DimDate[year]
